import { StyleSheet } from "react-native";

const authStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#030E38",
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 20,
    },
        fontSize: 55,
        fontWeight: "bold",
        color: "#fff",
        marginBottom: 40,
    },
        color: "#fff",
        fontSize: 24,
        marginBottom: 30,
    },
        fontSize: 16,
        fontWeight: "normal",
        textAlign: "left",
        textAlignVertical: "top",
        color: "#FAFAFA",
    },
        marginBottom: 5,
    },
        height: 50,
        borderWidth: 1,
        borderRadius: 9,
        paddingHorizontal: 10,
    },
        width: "90%",
        marginBottom: 15,
    },
    signInButton: {
        backgroundColor: "#1E6AFF",
        width: "90%",
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: "center",
        marginBottom: 20,
    },
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    forgotPassword: {
        alignSelf: "flex-end",
        color: "#ccc",
        marginBottom: 20,
    },
        flexDirection: "row",
        alignItems: "center",
        width: "80%",
        marginVertical: 20,
    },
        flex: 1,
        height: 1,
        backgroundColor: "#ccc",
    },
    dividerText: {
        marginHorizontal: 10,
        color: "#ccc",
    },
    socialContainer: {
        flexDirection: "row",
        width: "80%",
        justifyContent: "space-evenly",
        marginBottom: 20,
    },
        borderRadius: 30,
        width: 60,
        height: 60,
        marginHorizontal: 20,
    },
        color: "#ccc",
        fontSize: 14,
    },
        color: "#1E6AFF",
        fontWeight: "bold",
    },
});

export default authStyles;
